version: '3.7'

services:
    app:
        build: .
        container_name: streamlit_app
        command: streamlit run src/main.py
        volumes:
            - .:/app
        ports:
            - "8501:8501"